### ISSUE TITLE
CollectionView should inherit Collection.prototype methods at instantiation

### ISSUE THREAD

**Issue by cwohlman** [usefulio/collection-views#2]
Instead of assigning `Collection.prototype` methods on the `CollectionView.prototype` we should assign each method at instance instantiation, like so:

``` javascript
CollectionView = function (collection, options) {
  // ...
  _.each(Mongo.Collection.prototype, function (val, key) {
    if (typeof val === "function") {
      this[key] = function () {
        return this._mongoCollection[key].apply(this._mongoCollection, arguments);
      };
    }
  });
};
```

**Comment by vladbalan** [comment]
In this case we also need to assign `find`, `findOne`, `insert`, `update`, `remove` and `upsert` right after that, otherwise they get overwritten.

**Comment by cwohlman** [comment]
True
