### ISSUE TITLE
CollectionView should allow the developer to limit the fields which should be returned

### ISSUE THREAD

**Issue by cwohlman** [usefulio/collection-views#4]
In addition to narrowing the query, a collection view should optionally also narrow the fields returned by a query.

This may be more complex for several reasons, here are the goals:
1. Limiting the fields should use the same syntax as in the `Mongo.Collection.find` options.
2. Limiting fields should work with chained where calls, later calls to where should further restrict the fields returned.
3. Limiting fields should work when positive and negative instructions are added (e.g. `{name: 1, age: -1}`)
4. Limiting fields should not be applied to the update operator, but we should warn the developer about this. (There will be room for future improvement in this area)

Some examples:

``` javascript
Books.where({}, {name: 1}) // -> {_id: 'xxx', name: 'yyy'} all other properties are removed
Books.where({}, {name: -1}) // -> {_id: 'xxx', genre: 'yyy'} only the name property is removed
Books.where({}, {name: -1}).where({}, {genre: -1}) // -> {_id: 'xxx'} both name and genre are removed
Books.where({}, {name: -1}).where({}, {someField: 1}) // -> {_id: 'xxx', someField: 'zzz'} only someField field is preserved, all others are removed
Books.where({}, {name: 1}).where({}, {genre: 1}) // -> {_id: 'xxx'} all fields are removed
```

**Comment by vladbalan** [comment]
For consistency with the mongo and Meteor API's we should use `0` instead of `-1` for excluding fields

http://docs.meteor.com/#/full/fieldspecifiers

**Comment by cwohlman** [comment]
:+1: for looking this up

**Comment by vladbalan** [comment]
Regarding `4.`, is this the expected behavior for `remove` and `upsert`, too?

**Comment by cwohlman** [comment]
I don't really see any application for remove, but for v1 let's go ahead and warn the developer for all non-find methods.
